### ISSUE TITLE
Create code to determine if a lat/long point is within distance of a rectangle of coordinates

### ISSUE THREAD

**Issue by stephenthedev** [raghunat/hotspot#73]
# Story
- I should have an algorithm that determines whether or not a latitude/longitude rect (4 lat/long pairs) is within _n_ distance of a give lat/long pair

# Acceptance Criteria
- In any language, or pseudo code, create a function that is given the following arguments:
	- origin
		- An array of 2 floats	
	- rect
		- An array of 4 arrays, each of 2 floats
	- maxDistance
		- A float in number of feet or yards	

	
- It should take the above arguments and return true if the distance of origin and the rect is < maxDistance, and false if vice versa.

**Comment by stephenthedev** [comment]
@SamMc27 @rouge888 Sprint due Tuesday 3/28

**Comment by stephenthedev** [comment]
@SamMc27 @dreagle95 look at Ruiqan's PR, specifically the VB file. Let me know what you think

**Comment by dreagle95** [comment]
@raghunat I'm pretty sure the coordinates should be passed as parameters to the function rather than the function asking for user input.  I'm unfamiliar with visual basic so I may be reading it wrong, but it looks like the function is asking for user input for latitude and longitude coordinates.  The arithmetic seems fine (using distance formula correctly).  Has anyone successfully run the code yet?

**Comment by stephenthedev** [comment]
@rouge888 include instructions to run

**Comment by stephenthedev** [comment]
@rouge888 Up

**Comment by rouge888** [comment]
[Calc.zip](https://github.com/raghunat/hotspot/files/894966/Calc.zip)
This is the application for this code
